name: 'Stage'
description: 'Stage build'
inputs:
  from_artifact:
    description: If a previous stage already uploaded build artifacts, the stage will resume building
    required: true
  arm:
    description: Build arm binary
    required: false
    default: false
  gen_installer:
    description: Generate the installer after signing
    required: false
    default: false
  upload_final:
    description: Upload artifacts after installer creation and signing
    required: false
    default: false
outputs:
  finished:
    description: If a previous stage already finished the build, the stage will set all output variables to the input ones and exit
  artifact_id:
    description: id of the build dir artifact
  version:
    description: version of the helium release we just built
  files-to-sign:
    description: Array of absolute path to files that should be signed

runs:
  using: 'node16'
  main: 'index.js'
